hyperskill_project:
  id: 167
  ide_files: https://cogniterra.org/media/attachments/lesson/25396/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Thu, 01 Jan 1970 00:00:00 UTC"
stages:
- id: 864
  step: 12374
  is_completed: true
- id: 865
  step: 12375
  is_completed: true
- id: 866
  step: 12376
  is_completed: false
- id: 867
  step: 12377
  is_completed: false
- id: 868
  step: 12378
  is_completed: false
topics:
  0:
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Files
    theory_id: 13025
  - title: File types
    theory_id: 13017
  - title: Working with file modes and permissions
    theory_id: 13961
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Load module
    theory_id: 6019
  - title: Create module
    theory_id: 6057
  - title: Packages
    theory_id: 6384
  - title: Taking input
    theory_id: 5913
  - title: Naming variables
    theory_id: 5885
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Pip
    theory_id: 6230
  - title: Virtual Environment
    theory_id: 13923
  - title: For loop
    theory_id: 6065
  - title: While loop
    theory_id: 5940
  - title: Elif statement
    theory_id: 5926
  - title: PyCharm basics
    theory_id: 6193
  - title: Introduction to databases
    theory_id: 8497
  - title: What is SQL
    theory_id: 7054
  - title: Basic data types
    theory_id: 7123
  - title: Literals
    theory_id: 7400
  - title: Arithmetic expressions
    theory_id: 7409
  - title: Running Python applications in PyCharm
    theory_id: 19153
  - title: Basic CREATE statement
    theory_id: 9084
  - title: Basic INSERT statement
    theory_id: 9059
  - title: The NULL value
    theory_id: 7907
  - title: Intro to MySQL
    theory_id: 16662
  - title: Command line arguments
    theory_id: 7981
  - title: Introduction to Linux
    theory_id: 9526
  - title: File modes and permissions
    theory_id: 13953
  - title: Files in Python
    theory_id: 8691
  - title: Reading files
    theory_id: 8139
  - title: Writing files
    theory_id: 8334
  - title: Context manager
    theory_id: 8702
  - title: Basic data types
    theory_id: 5852
  - title: Variables
    theory_id: 5859
  - title: Invoking a function
    theory_id: 5891
  - title: Integer arithmetic
    theory_id: 5865
  - title: Declaring a function
    theory_id: 5900
  - title: List
    theory_id: 5979
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: String formatting
    theory_id: 6037
  - title: Arguments
    theory_id: 7248
  - title: Indexes
    theory_id: 6189
  - title: Dictionary
    theory_id: 6481
  - title: Dictionary methods
    theory_id: 9008
  - title: Operations with dictionary
    theory_id: 11096
  - title: Basic string methods
    theory_id: 6842
  - title: Type casting
    theory_id: 6224
  - title: Escape sequences
    theory_id: 7130
  - title: Split and join
    theory_id: 6972
  - title: List comprehension
    theory_id: 6315
  - title: Alter table
    theory_id: 9579
  - title: PRIMARY KEY constraint
    theory_id: 9781
  1:
  - title: FOREIGN KEY constraint
    theory_id: 9789
  2:
  - title: Relational Data Model
    theory_id: 13785
  - title: Basic SELECT statement
    theory_id: 7392
  - title: SELECT FROM statement
    theory_id: 8611
  - title: Logic and comparison expressions
    theory_id: 8619
  - title: Results ordering
    theory_id: 8627
  - title: Types of JOINs
    theory_id: 12100
  - title: Inserting selected rows
    theory_id: 9595
  - title: ER-diagrams
    theory_id: 13247
  4:
  - title: Special WHERE operators
    theory_id: 10521
  - title: Argparse module
    theory_id: 11389
  - title: Set operations
    theory_id: 9798
  - title: Operations with list
    theory_id: 6031
  - title: Nested lists
    theory_id: 6938
  - title: Set
    theory_id: 6643
  - title: Set operations
    theory_id: 8991
